server:
  port: 8083

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # issuer-uri: http://localhost:8443/auth/realms/appdevelopers
          jwk-set-uri: http://localhost:8443/realms/appdevelopers/protocol/openid-connect/certs
